name: Production - Website Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - "XXX"
      - 'AAA/**'
  pull_request:
    branches:
      - "XXX"
      - 'AAA/**'

jobs:
  build_and_deploy:
    uses: ./.github/workflows/_cd-site-front.yml
    with:
      grifClient: 'EYEMASTERS'
      grifEnvironment: 'Production'
      grifLoginMode: 'SVCPRIN'
      GrifProjName: 'eyemasters-site'
      GrifSvcName: 'website'
    secrets:
      GRIF_HOST_AZPRIN: ${{ secrets.OPMAD911AZPRIN }}
      GRIF_HOST_AZPWD: ${{ secrets.OPMAD911AZPWD }}
